# .github/workflows/ci.yml
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --frozen
      - name: Lint & typecheck (optional if added)
        run: |
          uv run ruff check .
          uv run mypy rentpigeon || true
      - name: Unit tests (when you add them)
        run: uv run pytest -q
